version: '3.8'
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: contacts
      MYSQL_USER: LXQgdmlzaGFsCg==
      MYSQL_PASSWORD: LXQgTXlwYXNzQG15c3FsMTIK
      MYSQL_ROOT_PASSWORD: LXQgYWRtaW5wYXNzCg==